version: '3'
services:

  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - "./data:/var/www/html:rw"
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    volumes:
      - "./data:/var/www/html:rw"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
  
  mariadb:
    build: ./requirements/mariadb/
    ports:
      - "3307:3307"
    volumes:
      - "./data:/var/www/html:rw" # err
    networks:
      - backend
    restart: always

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
